# .sops.yaml
keys:
  - &admin "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJQgPPuvnBiaK6z3ADBqY5l11oB6HHwm1rtUAEusMSlx root"
  - &sudhassh "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAPOVwS487rUg6zfTKdeRILuaF2MAkj+0Hb+VybiY/MK sudha"
  - &sudhalaptopssh "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOJRuZDBhEn9Q37C0qZ8jMo6EMrTe7bzTT4hKcBMBN9 sudhalaptop"

creation_rules:
  # --- MACHINE: LAPTOP ---
  - path_regex: modules/machines/laptop/laptopsecrets.yaml$
    key_groups:
      - age:
          - *admin
          - *sudhalaptopssh

  # --- USER: SUDHA ---
  - path_regex: modules/users/sudha/sudhasecrets.yaml$
    key_groups:
      - age:
          - *admin
          - *sudhalaptopssh
          - *sudhassh
