keys:
  - &admin age1keca023xe9nya8yqfdx5ca32w57m8k8galwthuzndlvehngmt93suu330j
  - &nryn-laptop-boot age19ywmcp2xzqy6ah49677rpknlqnwzmwv5sc70kdmnsk34j2ept3eslga8p2
  - &nryn-server-boot age1jc82vp8wu4csds6tuhqkg8mesuku5plzp6n3v9xkg5vewcsu93jq63cjlc

creation_rules:
  - path_regex: secrets/nryn-laptop.yaml$
    key_groups:
      - age:
          - *admin  
          - *nryn-laptop-boot
  - path_regex: secrets/nryn-server.yaml$
    key_groups:
      - age:
          - *admin
          - *nryn-laptop-boot
          - *nryn-server-boot
          
